### ISSUE TITLE
One Provider Two+ Referrers

### ISSUE THREAD

**Issue by rileydjohnson** [radremedy/radremedy#112]
Got to thinking on train this morning.. I think we talked about this very early, but I want to make sure we thought about how we will handle circumstances where two or more data sources have a provider in common? Case in point: Looking for Jane Smith, MD who is a recommended provider from ABC and XYZ. How do we make it (or can we make it) so Jane Smith, MD has one provider page instead of two entries?

**Comment by radioprotector** [comment]
Is there any action that we can take on this, given that we have duplicate detection and I created a separate issue (#211) for organizational logins?

**Comment by radioprotector** [comment]
Our current concept of organizational logins, as tracked in #211, will address this.

I think we'll have our list of resources, our list of organizations (as user accounts, most likely), and we'll have a table that stores associations between the two, so that a resource can be listed/endorsed/whatevered by multiple organizations. We'll list out each associated organization in a separate section on the provider page.
