### ISSUE TITLE
Small Changes

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#179]
After the most recent deployment, people besides @radioprotector and @AllieDeford had some thoughts on tweaks for the site. It would be good to post those issues here

**Comment by lovecultivated** [comment]
Small Nitpicky Changes:

HOMEPAGE
- Logo (I know you have been working on it, but still important)
- The search RAD toolbar search box isn't centered, but positioned slightly towards the bottom
- I am not sold on the color(s) of the "Click for Introduction" box - maybe white text instead? Or white text with the blue background?
- Should "Search RAD" be bigger so it is the same size as the search box?
- Can we change the font size on the "Submit" and "Search" text in those boxes? 
- Thoughts about sliding the "Search" button over to the right hand side? From a UX perspective, that is where I look for it

Menu!
- Lets shorten it
* Donate to keep RAD going (or somethign like that)
* How to use RAD (maybe this should replace the "Intro to RAD" thing on the upper right toolbar)
* About RAD Remedy
* Projects
* Get Involved
* Contact Us
* Login or Sign Up (should this also be on the top right hand corner of all the screens? I feel like that is where we look for those things instinctively)

For serious question - from a UX perspective - I feel like some of these menu items are repetitive with other areas on the page that are, or can be, static on the rest of the site. What are your thoughts on that, Allie?

Also, I have been wondering about mini graphics to put next to each menu item (sort of like on the provider pages) to jazz it up (so to speak). Especially for the Donate part, but it would look silly to have  only one, I think.

**Comment by lovecultivated** [comment]
Bottom of all the pages: Can we center the social media links to the Connect with RAD on Social Media? They are sort of hanging off on one side...

SEARCH RESULTS
- I feel like there needs to be more information - maybe their category and city/state underneath the bolded name
- If that happens, a larger space between new providers to visually separate them more

PROVIDER PAGES (based off of Allie's new wireframes in Dropbox)

Overall, I like this layout. I think it makes it clearer. There are some small things (ICATH and WPATH standards are two different things and providers can use none, one or the other, or both, depending) and I think that that top checkmark section needs to be a bit smaller. I would like to see and Org name listed (smaller and not bold) under the Provider Name (if applicable). There are a couple of things that will need to be added in the future, but I think it is doable in this format. (Services, for example).

The review section will also need to be sussed out a bit more, but also doable in this format.

PROJECTS PAGE
Looks good. Except I want a bigger visual space between the projects (because I, apparently, *always* want a bigger visual space between everything that isn't under the same thing)

CONTACT US:
I think we will also want to put in personal contact information for a couple of people when we get going... along the lines of "Have an outreach question? Contact Rachel!" or some crap.

DONATE:
Needs to be more exciting, IMO. I blame Riley. But maybe some graphics like we are seeing on the provider pages... "Reoccuring" "Paypal" "Check" or something. 

We should also add a blurb about what donations will cover. Storytelling is powerful. This is also a Riley job.

**Comment by AllieDeford** [comment]
Dan says: 

Yeah, logo, but Also banner.

I like rachels idea for the menu. also, yeah i think login at top right feels more intuitive, and can be removed from menu. new to rad can go- the ‘how to use rad’ or however you want to phrase it, can live in the menu bar.

can type on menu bar be a bit bigger, or possibly the width of the menu a tad smaller? feels a little overwhelming with the purple. Q… should width of nag bar be changing when window is resized? idk if that’s necessary or not?

currently only the text on the nav bar has a hover… would it be crazy difficult to make it more like a hover field over the block? as if they were buttons, perhaps.

type on search button should be a bit bigger

connect with social media text isn’t centered

idk if we need help keep read going! donate here! at the bottom as well as in the nav bar. Thoughts?




login page

‘forgot your password? request a reset’ a bit bigger. also maybe extend hover to include ‘forgot your password’.

——— from the reset password page, should it say username? what if i don’t remember my username either? how about just reset via email?

can sign up be combined into the login page? make it an option like ‘don’t have an account? sign up here!’. i don’t think it needs to be its link in the menu necessarily.

also, is there an option to create an account as a provider/individual/org?





get involved page
i feel like it should say ‘rad’ skills instead of ‘mad’ skills. haaaaaaaaaaaaaaaaaaaaaha.

is there a way to integrate the volunteer form directly onto that page so that it’s not an external link?

also, that banner still needs to be fixed. the arrows under the text are really distracting.

**Comment by AllieDeford** [comment]
What do you want from the logo, exactly? You both just said "The logo" and, unfortunately, I can't yet read minds XD

**Comment by lovecultivated** [comment]
I just said the logo because we had talked about it before, but it is super
small. I know the issue has been that we are struggling with it on small
screens, yeah? But it is important enough visually to mention...

:-)

**Comment by AllieDeford** [comment]
Re: Menu 

I think that's still too many items. If it were me, I would do this: 

Advanced Search 
How to use RAD (maybe this should replace the "Intro to RAD" thing on the upper right toolbar)
About 
  --Projects
  --Get Involved
Contact Us

But also.... I've been thinking. This whole time, I've been a proponent of the continued vertical menu. @radioprotector fought me on it, but I persisted. And..... I think I changed my mind? I feel like a number of our sizing/presentation issues are due to the side menu. Also, other sites that have the same underlying structure we do often have horizontal nav. See [Yelp](www.yelp.com/), [UrbanSpoon](www.urbanspoon.com), [RateMDs](https://www.ratemds.com), and [Angie's List](http://www.angieslist.com/) to name a few. It's cleaner, easier to display on small screens with less work, an a number of other things. Thoughts?


Login or Sign Up (should this also be on the top right hand corner of all the screens? I feel like that is where we look for those things instinctively)
Donate to keep RAD going (or somethign like that)

**Comment by radioprotector** [comment]
You know my feelings. ;)

The cool thing about Bootstrap's navbar (which I think is horizontal-only) is that you [can use dropdowns](http://getbootstrap.com/components/#navbar) as part of the nav structure, so we could have just an "About RAD" menu item but with a dropdown that also includes links to the "Projects", "Donate", and "Get Involved" pages. (I'm assuming we could use a [split dropdown](http://getbootstrap.com/components/#btn-dropdowns-split) to still have the "About RAD" link separate from toggling the dropdown.)

**Comment by AllieDeford** [comment]
YOU HAVE CONVERTED ME, GREAT REVEREND :D

**Comment by lovecultivated** [comment]
Golden rule of npo online presence is to make donation references as often
and as visible as we can without it being obnoxious, so that definitely
needs to stay as its own menu item.

I am fine with either vertical or horizontal.

Re: Menu

I think that's still too many items. If it were me, I would do this:

Advanced Search
How to use RAD (maybe this should replace the "Intro to RAD" thing on the
upper right toolbar)
About
--Projects
--Get Involved
Contact Us

But also.... I've been thinking. This whole time, I've been a proponent of
the continued vertical menu. @radioprotector
<https://github.com/radioprotector> fought me on it, but I persisted.
And..... I think I changed my mind? I feel like a number of our
sizing/presentation issues are due to the side menu. Also, other sites that
have the same underlying structure we do often have horizontal nav. See Yelp
<http://www.yelp.com/>, UrbanSpoon <http://www.urbanspoon.com>, RateMDs
<https://www.ratemds.com>, and Angie's List <http://www.angieslist.com/> to
name a few. It's cleaner, easier to display on small screens with less
work, an a number of other things. Thoughts?

Login or Sign Up (should this also be on the top right hand corner of all
the screens? I feel like that is where we look for those things
instinctively)
Donate to keep RAD going (or somethign like that)

—
Reply to this email directly or view it on GitHub
<https://github.com/radremedy/radremedy/issues/179#issuecomment-85804617>.

**Comment by rileydjohnson** [comment]
Ditto. I don't care which we do so long as we are consistent across
platforms and things work. Thanks team!
