### ISSUE TITLE
Add 'verified on' field to RAD record format

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#212]
@lovecultivated has requested a new field in RAD record that called 'verified on'. The idea is that some of the resources have been contacted (called/people have been contacted to verify that information is correct) and it would be nice to keep track of that. The field would default to 'not verified' (or something like that based on the type of the column), and it would only be updateable for now via the admin panel. From the admin panel, the date could be updated to any date. 

I think this is a good idea, and she promises it will be the last change for a while :)

**Comment by radioprotector** [comment]
This will be a little more of a pain than initially anticipated, I think, because Python doesn't have a standard library function for parsing a date string with an unspecified format. We could use [strptime](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime) to parse it, but that requires a defined format (such as `YYYY-MM-DD`).

If we're OK with enforcing a standard for parsing out dates, we could go that route and change `radrecord.is_valid` to enforce that for non-empty `verified_on` fields.

Otherwise, we'd have to use an external library like [dateutil](https://labix.org/python-dateutil#head-c0e81a473b647dfa787dc11e8c69557ec2c3ecd2) which I'm not wild about.

Outside of that, I think this would just be a standard date field (with no time component) and we'd want to add some Admin support for filtering on this date. It would also be nice to have an "Unverified" view with support for marking resources as verified en-masse.

**Comment by radioprotector** [comment]
After some email discussion, it appears that it'd be easiest to support `MM-DD-YYYY` format. 

I want to also support `YYYY-MM-DD` (as that's the typical [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601#Dates) for dates).

**Comment by radioprotector** [comment]
HOLD UP. We're going with just `YYYY-MM-DD` (thanks Rachel)!

**Comment by lovecultivated** [comment]
and blanks instead of "no" because reasons.

Rachel A. Hennessy
*Developmental Therapist*
*(773) 817-8044*

IMPORTANT: This electronic transmission contains confidential information,
some or all of which may be protected health information as defined by the
federal Health Insurance Portability & Accountability Act (HIPAA) Privacy
Rule. This transmission is intended for the exclusive use of the individual
or entity to which it is addressed and may contain information that is
proprietary, privileged, confidential and/ or exempt from disclosure under
applicable law.



If you are not the intended recipient (or an employee or agent responsible
for delivering this electronic transmission to the intended recipient), you
are herby notified that any disclosure, dissemination, distribution, or
copying if this information is strictly prohibited and may be subject to
legal restriction or sanction. Please notify the sender by telephone
(number listed above) to arrange the return or destruction of the
information and all copies.

**Comment by radioprotector** [comment]
The new 1.3.0 version of the radrecord format now supports a `date_verified` field. I don't want to make any further database changes while there's an outstanding PR, but I can start working on this once #218 has been merged.

**Comment by radioprotector** [comment]
I have the basic functionality together but I'm also using this as a point to ensure that the CSV import will work properly with our exported data. 

As I [mentioned in 215](https://github.com/radremedy/radremedy/issues/215#issuecomment-106152167), right now the results are... not promising. I'm currently attempting to wade through a lot of weird encoding and formatting issues and so that's really holding things up at this point.

**Comment by radioprotector** [comment]
Some examples:
![bad-data-1](https://cloud.githubusercontent.com/assets/8010294/7875665/d56fa2bc-058d-11e5-8240-d76987a88212.PNG)
![bad-data-2](https://cloud.githubusercontent.com/assets/8010294/7875666/d5727410-058d-11e5-81f5-618403aca8c8.PNG)

**Comment by radioprotector** [comment]
Okay, I tried a couple of things, such as using the [chardet](https://pypi.python.org/pypi/chardet) library to detect the encoding and the csv's [Sniffer](https://docs.python.org/2/library/csv.html#csv.Sniffer) functionality to attempt to detect the format used by the CSV file.

It turned out that the sniffer was causing more problems than it solved (the "name" column was disappearing from all records), but the use of the chardet library is necessary for handling encoding issues.
