### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#259]
We need to come up with a long term solution for sending email to/from radremedy.org address

**Comment by radioprotector** [comment]
We can easily add email addresses to our WebFaction account. We might need to impose some reasonable limits on mailbox size, if that's possible.

I think at the moment [it doesn't count against bandwidth quotas](https://community.webfaction.com/questions/17014/assuming-mail-being-relayed-through-webfaction-counts-as-bandwidth-usage/17016) so that shouldn't be a concern.

**Comment by radioprotector** [comment]
The only part remaining for this is cleaning up the mailbox management, which I will do once I receive confirmation emails from Riley, Rachel, and Dan.

**Comment by radioprotector** [comment]
All confirmed now.
