### ISSUE TITLE
Better method for selecting categories

### ISSUE THREAD

**Issue by AllieDeford** [radremedy/radremedy#276]
It's confusing right now, but we don't know how to make it better right now.

**Comment by radioprotector** [comment]
I think if we add some top-level groupings to the process it will be a little easier to comprehend. I'm in favor of dropping our current select2-based model to something like [Bootstrap Multiselect](https://davidstutz.github.io/bootstrap-multiselect/#getting-started), which retains the existing text searching that I like from select2 but also allows for some groupings.

Basically, both categories and populations should belong to an optional grouping, which will be a high-level category like "Therapy" or "Medical Specialists" - I'd also like to have a "Hormones/Endocrinology" section. We should have a configurable order for these different groupings so they show up in the list. Stuff without a grouping should go in at the top.

**Comment by internetcreep** [comment]
I like this. I am torn between whether the high-level groupings should be selectable or not. That would be outside of how we're currently doing categories, and I think most users wouldn't need them to be clickable. But organizations and case manager type folks might want to see all the therapy options (without having to click all the sub-options). 

Given some of the categorical changes thus far, I can get to work on what the specific groupings might entail.

**Comment by radioprotector** [comment]
There's an option that lets you make those groups clickable - clicking them will select/unselect the entire group. You can see an example next to "enableClickableOptGroups" on that page.

**Comment by internetcreep** [comment]
Yeah, I saw that you can do that. I was more so questioning if we *should* and if so how much re-configuring we will have to do as far as the already assigned resources.

**Comment by radioprotector** [comment]
Ah - I was imagining that these top-level groupings wouldn't be categories in and of themselves.

**Comment by internetcreep** [comment]
Ok. Cool. I guess that's what I was trying to get at (round-a-boutly). Follow-up: does this do the job of making all our categories more navigable? Cause we still have a bunch, and I worry that this is still a big checklist. Thought: would it make sense for each of the top-level groups be in it's own option box or something? Ex. Medical Specialties, Mental Health, Complementary Medicine, Social Services, etc.

**Comment by radioprotector** [comment]
I like the text searching - I think that will help if we keep that around. Select2 gives us that but right now I think it's falling down in making the list of categories otherwise browsable, and I'm hoping that the groupings will help with that.

I'm worried about adding too many initial searching options if we break them out into separate select boxes.

**Comment by radioprotector** [comment]
## Database Changes

From a database perspective, we will add new `CategoryGroup` and `PopulationGroup` models with the following columns:

- `id`: Integer, PK, identity, not null
- `name`: UnicodeText(100), not null, unique
- `description`: UnicodeText, nullable
- `order`: Float, default to 0.0
- `date_created`: DateTime, default to datetime.utcnow

Each will have a `categories`/`populations` relationship with `lazy='dynamic'` and `ondelete='SET NULL'` configured. These will have backrefs to the `Category`/`Population` models with the name `grouping`.

To simplify things, the visibility of these items cannot be toggled. Since the above relationships will null out the associated group for any contained categories/populations on deletion, I think this is OK.

We will add a `grouping_id` (Integer, FK to CategoryGroup/PopulationGroup, nullable) column to the `Category` and `Resource` models. The backref to the group will be handled above by the relevant group model.

## Controller/Action Changes

### Admin

In Admin we will add standard `CategoryGroupView` and `ResourceGroupView` model views to allow for administration of these groups.

### Retrieving Grouped Categories/Populations

In `remedyblueprint.py` we will add `group_active_categories` and `group_active_populations`  methods. These will accept a flat list of categories/populations but return a grouped result.

This will use the following logic:
- All categories/populations without groups will go in at the top and be sorted by name.
- The distinct groups of all retrieved categories/populations will be retrieved and be sorted by order and name (ascending)
- All categories/populations with groupings will be placed in those ordered groups and be sorted by name within that grouping.

The methods will return data in the following structure:

```py
[
	('ID1', 'Ungrouped Item 1'),
	('ID2', 'Ungrouped Item 2'),
	(
		'Group 1',
		[
			('ID3', 'Item A in Group 1'),
			('ID4', 'Item B in Group 1')
		]
	),
	(
		'Group 2',
		[
			('ID4', 'Item C in Group 2'),
			('ID5', 'Item D in Group 2')
		]
	)
]
```

### Form Changes

We will add a custom WTForms field, `GroupedSelectMultipleField`, which will be based on the code available at a [Gist showing how this is done for single-selects](https://gist.github.com/playpauseandstop/1590178).

This field will be used on the following forms:
- `auth.forms.SignUpForm`
- `rad.forms.UserSettingsForm`

To reflect the fact that these are now groupings, the `population_choices` argument passed to the constructors for these forms will be renamed to `grouped_population_choices`.

In addition, because our above grouping methods will automatically convert the population options into the tuples needed by the field, we can directly assign this parameter to the `populations.choices` field without having to do any additional transformation on the provided populations.

Similarly, we'll rename the `categories` and `populations` template variables for the `remedyblueprint.resource_search` endpoint to `grouped_categories` and `grouped_populations` respectively.

## UI Changes

We will ditch the use of Select2 for client-facing fields and in its place use [Bootstrap Multiselect](https://davidstutz.github.io/bootstrap-multiselect/#getting-started), which will be configured with the following options:

- `enableClickableOptGroups`: true
- `includeSelectAllOption`: false
- `enableFiltering`: true
- `enableCaseInsensitiveFiltering`: true

We will encapsulate this configuration in a `Remedy.makeBootstrapMultiselect` JavaScript function.

This new widget will be used in the following areas:
- `create-account.html` (for Identities - did not use this previously)
- `settings.html` (for Identities - did not use this previously)
- `find-provider.html` (for Categories and Populations)

In the case of `create-account.html` and `settings.html`, we can rely on the existing WTForms scaffolding to handle rendering appropriately. We will have to update `find-provider.html` to manually render out these items, which I am hoping we can consolidate with the use of some macros.
